### ISSUE TITLE
Reload on .demosnippets file changed

### ISSUE THREAD

**Issue by clairernovotny** [mrlacey/DemoSnippets#5]
Related to #4, if one of the `.demosnippets` files changes in the solution (FileSystemWatcher?), it should update the tabs.

**Comment by mrlacey** [comment]
I want to understand the reasoning behind this request and what the user story is before implementing anything.

If authoring a `.demosnippets` file, why would you also want it loaded in the Toolbox?

If the need is to be able to update a file after it was initially authored and have the Toolbox reflect the change (maybe because it's during a demo) then this makes more sense.

My concern is that there will be lots of times when a file is originally being authored that it will be saved and so lots of background work will be done for no real benefit, but with the _potential_ to cause VS to run slow for a second each time the file is saved and the toolbox updated.

If this was implemented it should be optional.
I'd also want to put a context menu on the file editor to implement this manually.
Should do #6 first.

**Comment by clairernovotny** [comment]
The main thing I’m thinking about is the demo authoring stage, as I take code out of the project and put it into the snippet file. I can see myself wanting to test the drag/drop and tweaking the appearance of the tab/snippet names based on how they appear in the toolbox.

**Comment by mrlacey** [comment]
> The main thing I’m thinking about is the demo authoring stage, as I take code out of the project and put it into the snippet file. I can see myself wanting to test the drag/drop and tweaking the appearance of the tab/snippet names based on how they appear in the toolbox.

Good to know. Thanks

**Comment by mrlacey** [comment]
Note to self: This will require the ability to remove all entries from the original file.

**Comment by mrlacey** [comment]
Enabled by default.

Can be disabled.
![image](https://user-images.githubusercontent.com/189547/51110813-d0d9c280-17f1-11e9-841d-a4fbeb337d9c.png)

If disabled, this option may also be useful

![image](https://user-images.githubusercontent.com/189547/51112568-f6b59600-17f6-11e9-89fe-db9c8c2f1296.png)

**Comment by mrlacey** [comment]
Will be in v1.3 - available from the marketplace shortly.

**Comment by clairernovotny** [comment]
Awesome! Are you going to blog/tweet about this to get the word out?
